import type { Pack } from "../types";

/** BANK — банковский пак. Fact: bank_facts bf; справочники branches/bank_products. */
export const bankPack: Pack = {
  id: "bank",
  title: { ru: "Банк", kk: "Банк" },
  factTable: "bank_facts bf",
  timeField: "bf.d",
  joins: [
    { table: "branches br", on: "bf.branch_id = br.id" },
    { table: "bank_products p", on: "bf.product_id = p.id" },
  ],
  rbacDimension: "region",
  defaultMetric: "issued",
  metrics: {
    issued: {
      id: "issued",
      title: { ru: "Выдачи", kk: "Берілген несие" },
      sqlExpr: "SUM(bf.issued_amount)",
      format: "money",
      goodDirection: "up",
    },
    balance: {
      id: "balance",
      title: { ru: "Остатки", kk: "Қалдық" },
      sqlExpr: "SUM(bf.balance)",
      format: "money",
      goodDirection: "up",
    },
    avg_issued: {
      id: "avg_issued",
      title: { ru: "Средняя выдача", kk: "Орташа берілген несие" },
      sqlExpr: "AVG(bf.issued_amount)",
      format: "money",
      goodDirection: "up",
    },
  },
  dimensions: {
    month: { id: "month", title: { ru: "Месяц", kk: "Ай" }, sqlExpr: "strftime('%Y-%m', bf.d)", kind: "time", grains: ["month"] },
    quarter: { id: "quarter", title: { ru: "Квартал", kk: "Тоқсан" }, sqlExpr: "strftime('%Y', bf.d) || '-Q' || ((CAST(strftime('%m', bf.d) AS INTEGER) + 2) / 3)", kind: "time", grains: ["quarter"] },
    year: { id: "year", title: { ru: "Год", kk: "Жыл" }, sqlExpr: "strftime('%Y', bf.d)", kind: "time", grains: ["year"] },
    branch: { id: "branch", title: { ru: "Филиал", kk: "Филиал" }, sqlExpr: "br.name", kind: "category" },
    region: { id: "region", title: { ru: "Регион", kk: "Аймақ" }, sqlExpr: "br.region", kind: "category" },
    city: { id: "city", title: { ru: "Город", kk: "Қала" }, sqlExpr: "br.city", kind: "category" },
    product: { id: "product", title: { ru: "Продукт", kk: "Өнім" }, sqlExpr: "p.name", kind: "category" },
    product_type: { id: "product_type", title: { ru: "Тип продукта", kk: "Өнім түрі" }, sqlExpr: "p.type", kind: "category" },
  },
  synonyms: {
    issued: ["выдачи", "выдача", "выдано", "выданных", "кредиты выданы", "берілген несие", "issued"],
    balance: ["остаток", "остатки", "остатков", "баланс", "қалдық", "balance"],
    avg_issued: ["средняя выдача", "средний кредит", "орташа несие"],
    branch: ["филиал", "филиалы", "филиалам", "отделение", "отделения"],
    region: ["регион", "регионы", "регионам", "аймақ", "область"],
    city: ["город", "города", "қала"],
    product: ["продукт", "продукты", "продуктам", "өнім", "депозит", "кредит", "ипотека", "автокредит", "карта"],
    product_type: ["тип продукта", "тип", "депозиты", "кредиты", "карты"],
    month: ["месяц", "месяцам", "помесячно", "ай", "по месяцам"],
    quarter: ["квартал", "кварталам", "тоқсан"],
    year: ["год", "годам", "жыл", "годовой"],
  },
  sampleQuestions: [
    { ru: "Выдачи по месяцам за последний год", kk: "Өткен жылдағы айлар бойынша берілген несие" },
    { ru: "Топ-5 филиалов по выдачам в 2026", kk: "2026 жылы берілген несие бойынша топ-5 филиал" },
    { ru: "Выдачи по продуктам за последний год", kk: "Өнімдер бойынша берілген несие" },
    { ru: "Остатки по филиалам", kk: "Филиалдар бойынша қалдық" },
    { ru: "Выдачи по регионам за 2026", kk: "2026 жылы аймақтар бойынша берілген несие" },
    { ru: "Выдачи по типам продуктов", kk: "Өнім түрлері бойынша берілген несие" },
    { ru: "Динамика выдач по кварталам" },
    { ru: "Топ-10 филиалов по остаткам" },
    { ru: "Выдачи по городам" },
    { ru: "Средняя выдача по продуктам" },
    { ru: "Как менялись остатки по месяцам?" },
    { ru: "Доля продуктов в выдачах" },
  ],
};
