import type { Pack } from "../types";

/** RETAIL — ритейл-пак. Fact: retail_sales rs; справочники stores/categories. */
export const retailPack: Pack = {
  id: "retail",
  title: { ru: "Ритейл", kk: "Ритейл" },
  factTable: "retail_sales rs",
  timeField: "rs.d",
  joins: [
    { table: "stores st", on: "rs.store_id = st.id" },
    { table: "categories c", on: "rs.category_id = c.id" },
  ],
  rbacDimension: "region",
  defaultMetric: "revenue",
  metrics: {
    revenue: {
      id: "revenue",
      title: { ru: "Выручка", kk: "Түсім" },
      sqlExpr: "SUM(rs.revenue)",
      format: "money",
      goodDirection: "up",
    },
    units: {
      id: "units",
      title: { ru: "Продажи, шт", kk: "Сатылым, дана" },
      sqlExpr: "SUM(rs.qty)",
      format: "number",
      goodDirection: "up",
    },
    returns: {
      id: "returns",
      title: { ru: "Возвраты, шт", kk: "Қайтарым, дана" },
      sqlExpr: "SUM(rs.returns_qty)",
      format: "number",
      goodDirection: "down",
    },
    avg_check: {
      id: "avg_check",
      title: { ru: "Средний чек", kk: "Орташа чек" },
      sqlExpr: "SUM(rs.revenue) * 1.0 / NULLIF(SUM(rs.qty), 0)",
      format: "money",
      goodDirection: "up",
    },
  },
  dimensions: {
    month: { id: "month", title: { ru: "Месяц", kk: "Ай" }, sqlExpr: "strftime('%Y-%m', rs.d)", kind: "time", grains: ["month"] },
    quarter: { id: "quarter", title: { ru: "Квартал", kk: "Тоқсан" }, sqlExpr: "strftime('%Y', rs.d) || '-Q' || ((CAST(strftime('%m', rs.d) AS INTEGER) + 2) / 3)", kind: "time", grains: ["quarter"] },
    year: { id: "year", title: { ru: "Год", kk: "Жыл" }, sqlExpr: "strftime('%Y', rs.d)", kind: "time", grains: ["year"] },
    store: { id: "store", title: { ru: "Магазин", kk: "Дүкен" }, sqlExpr: "st.name", kind: "category" },
    region: { id: "region", title: { ru: "Регион", kk: "Аймақ" }, sqlExpr: "st.region", kind: "category" },
    city: { id: "city", title: { ru: "Город", kk: "Қала" }, sqlExpr: "st.city", kind: "category" },
    category: { id: "category", title: { ru: "Категория", kk: "Санат" }, sqlExpr: "c.name", kind: "category" },
  },
  synonyms: {
    revenue: ["выручка", "выручку", "выручке", "доход", "оборот", "түсім", "revenue"],
    units: ["продажи", "продано", "штук", "количество", "сатылым", "сату", "units"],
    returns: ["возврат", "возвраты", "возвратов", "қайтарым", "returns"],
    avg_check: ["средний чек", "чек", "орташа чек"],
    store: ["магазин", "магазины", "магазинам", "дүкен", "точка"],
    region: ["регион", "регионы", "регионам", "аймақ", "область"],
    city: ["город", "города", "қала"],
    category: ["категория", "категории", "категорий", "категориям", "санат", "товар"],
    month: ["месяц", "месяцам", "помесячно", "ай", "по месяцам"],
    quarter: ["квартал", "кварталам", "тоқсан"],
    year: ["год", "годам", "жыл", "годовой"],
  },
  sampleQuestions: [
    { ru: "Выручка по месяцам за последний год", kk: "Өткен жылдағы айлар бойынша түсім" },
    { ru: "Топ-5 магазинов по выручке в 2026", kk: "2026 жылы түсім бойынша топ-5 дүкен" },
    { ru: "Продажи по категориям за последний год", kk: "Санаттар бойынша сатылым" },
    { ru: "Возвраты по категориям", kk: "Санаттар бойынша қайтарым" },
    { ru: "Выручка по регионам за 2026", kk: "2026 жылы аймақтар бойынша түсім" },
    { ru: "Средний чек по магазинам", kk: "Дүкендер бойынша орташа чек" },
    { ru: "Динамика выручки по кварталам" },
    { ru: "Топ-10 магазинов по продажам" },
    { ru: "Выручка по городам" },
    { ru: "Продажи по категориям за последний квартал" },
    { ru: "Как менялись возвраты по месяцам?" },
    { ru: "Доля категорий в выручке" },
  ],
};
